"""add model_store and training_data

Revision ID: 142b37ecac99
Revises: 0f2c354a38c4
Create Date: 2026-05-04 12:46:37.400009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142b37ecac99'
down_revision: Union[str, Sequence[str], None] = '0f2c354a38c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_store',
    sa.Column('version_id', sa.String(length=50), nullable=False),
    sa.Column('binary_state', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('accuracy_log', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('pixel_data_path', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_data_id'), 'training_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_data_id'), table_name='training_data')
    op.drop_table('training_data')
    op.drop_table('model_store')
    # ### end Alembic commands ###
